image: node:20.10.0

stages:
  - lint
  - build
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install

prettier:
  stage: lint
  script:
    - pnpm run lint

build_svelte:
  stage: build
  variables:
    CF_PAGES: 1
  script:
    - pnpm run build
  artifacts:
    paths:
      - .svelte-kit/cloudflare

cf_pages:
  stage: deploy
  script:
    - pnpm dlx wrangler pages deploy ".svelte-kit/cloudflare" --project-name prajeen --branch $CI_COMMIT_REF_NAME
